baseURL = "https://jereme.me"

defaultContentLanguage = "en"

languageCode = "en"
title = "Jereme Causing"

# Change the default theme to be use when building the site with Hugo
theme = "FixIt"
weight = 1
# language code
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

