[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.4"
  HUGO_ENABLEGITINFO = "true"
  TZ = "Asia/Manila"

[[redirects]]
  from = "https://jereme.netlify.app/*"
  to = "https://jereme.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/curriculum-vitae"
  to = "/cv"
  status = 301
  force = false

[[redirects]]
  from = "/post/*"
  to = "/posts/:splat"
  status = 301
  force = false
